apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-apps-process-video
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: process-video-app-container
          image: migprogrammer/process-videos:latest
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: app-process-video-configmap