openapi: 3.0.0
info:
  title: Swagger Process Video - OpenAPI 3.0
  description: |-
    <b>Fiap Challenge Hackaton</b> - Phase 5 - ProcessVideo Project
  termsOfService: http://swagger.io/terms/
  contact:
    email: miguel.silva@mackenzista.com.br
  version: 0.0.2

tags:

  - name: process-videos
    description: "Processa videos"

paths:

  /process/video/:
    post:
      tags:
        - process-videos
      summary: Recebe uma lista de videos
      description: Recebe uma lista de videos para processamento
      operationId: process
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: successful operation


components:
  schemas:

    PedidoRequestDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        idCliente:
          type: integer
          format: int64
        itensPedido:
          type: array
          items:
            $ref: '#/components/schemas/ItemPedido'

    ItemPedido:
      type: object
      properties:
        id:
          type: integer
          format: int64
        idPedido:
          type: integer
          format: int64
        produto:
          $ref: '#/components/schemas/ProdutoDTO'

    ProdutoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        preco:
          type: number
          format: double
        categoria:
          $ref: '#/components/schemas/CategoriaDTO'
        descricao:
          type: string
        img:
          type: string

    AcompanhamentoResponseDTO:
      type: object
      properties:
        pedido:
          $ref: '#/components/schemas/PedidoRequestDTO'
        status:
          $ref: '#/components/schemas/StatusPedidoDTO'
        total:
          type: number
          format: double

    StatusPedidoDTO:
      type: string
      enum:
        - RECEBIDO
        - EM_PREPARACAO
        - PRONTO
        - FINALIZADO

    CategoriaDTO:
      type: string
      enum:
        - LANCHE
        - ACOMPANHAMENTO
        - BEBIDA
        - SOBREMESA