name: Continuous Inntegration and Continuous Delivery

on:
  push:
    branches:
      - developer
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
    
  build:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Run Units, Integration And System
        run: mvn test

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Build the Docker image
        run: docker build -t migprogrammer/process-video:latest .

      - name: Log into Docker Hub
        run: docker login -u migprogrammer -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push image to Docker Hub
        run: docker push migprogrammer/process-video:latest
